version: "3.8"

services:
  orders:
    build: .
    ports:
      - "8001:8001"
    volumes:
          - ./:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
